run:
  concurrency: 4
  issues-exit-code: 1
  tests: false

output:
  formats:
    - format: tab
      path: stdout

linters:
  disable-all: true
  enable:
    - canonicalheader
    - copyloopvar
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - goprintffuncname
    - grouper
    - inamedparam
    - mirror
    - nilerr
    - nosprintfhostport
    - protogetter
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - govet
    - unconvert
    - ineffassign
    - typecheck
    - gosec
    - gosimple
    - staticcheck
    - unused
    - gofmt
    - gocritic
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - goimports
    - asasalint
    - bidichk
    - dogsled
    - errorlint
    - forbidigo
    - loggercheck
    - makezero
    - nakedret
    - nilnil
    - promlinter
    - reassign
    - tenv
    - unparam
    - asciicheck
    - containedctx
    - usestdlibvars
    - noctx
    - spancheck
    - perfsprint
    - prealloc
    - durationcheck
    - errchkjson
    - errname
    - errcheck
    - exptostd
    - nilnesserr
    - usetesting

  enable-all: false
  disable: []

  #  presets:
  #    - bugs
  #    - unused

  fast: false

linters-settings:
  gocritic:
    # Disable all checks.
    # Default: false
    disable-all: true
    # Which checks should be enabled in addition to default checks; can't be combined with 'disabled-checks'.
    # By default, list of stable checks is used (https://go-critic.github.io/overview#checks-overview):
    enabled-checks:
      - appendAssign
      - argOrder
      - badCall
      - badCond
      - badLock
      - badRegexp
      - badSorting
      - builtinShadowDecl
      - caseOrder
      - codegenComment
      - deferInLoop
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - emptyDecl
      - evalOrder
      - exitAfterDefer
      - externalErrorReassign
      - filepathJoin
      - flagDeref
      - flagName
      - mapKey
      - offBy1
      - regexpPattern
      - returnAfterHttpError
      - sloppyLen
      - sloppyTypeAssert
      - sortSlice
      - sprintfQuotedString
      - sqlQuery
      - syncMapLoadAndDelete
      - truncateCmp
      - unnecessaryDefer
      - weakCond
      - appendCombine
      - equalFold
      - indexAlloc
      - preferDecodeRune
      - preferStringWriter
      - preferWriteByte
      - rangeExprCopy
      - rangeValCopy
      - sliceClear
      - stringXbytes
      - boolExprSimplify
      - elseif
      - newDeref
      - regexpMust
      - singleCaseSwitch
      - switchTrue
      - typeSwitchVar
      - underef
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc
      - builtinShadow
      - captLocal
      - commentedOutImport
      - defaultCaseOrder
      - dupImport
      - exposedSyncMutex
      - httpNoBody
      - methodExprCall
      - stringConcatSimplify
      - timeExprSimplify
      - tooManyResultsChecker
      - typeAssertChain
      - typeUnparen
      - unnecessaryBlock

  errcheck:
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: false

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true

  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: false

  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/inDels/inDriverGO

issues:
  # Which files to exclude: they will be analyzed, but issues from them won't be reported.
  # There is no need to include all autogenerated files,
  # we confidently recognize autogenerated files.
  # If it's not, please let us know.
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  # Default: []
  exclude-files:
    - ".*._mock.go$"
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"

  # Which dirs to exclude: issues from them won't be reported.
  # Can use regexp here: `generated.*`, regexp is applied on full path,
  # including the path prefix if one is set.
  # Default dirs are skipped independently of this option's value (see exclude-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  # Default: []
  exclude-dirs:
    - genfiles$
    - vendor$
    - docs$

  exclude-rules:
    - linters:
        - godot
      source: "@\\w+" # Исключаем все строки, начинающиеся с @ (Swagger-аннотации)
