// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplateinternal = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
<<<<<<< HEAD
        "/cities": {
            "get": {
                "description": "Get all cities",
=======
        "/benefits": {
            "get": {
                "description": "Получить список всех льгот",
>>>>>>> main
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "Cities"
                ],
                "summary": "Get Cities",
=======
                    "Benefits"
                ],
                "summary": "Get Benefits List",
>>>>>>> main
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
<<<<<<< HEAD
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.City"
                            }
=======
                            "$ref": "#/definitions/v1.benefitsListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    }
                }
            }
        },
        "/benefits/{id}": {
            "get": {
                "description": "Получить льготу по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Benefits"
                ],
                "summary": "Get Benefit By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Benefit ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.benefitResponse"
>>>>>>> main
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    },
<<<<<<< HEAD
=======
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    },
>>>>>>> main
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    }
                }
            }
        },
        "/users/auth/callback": {
            "get": {
                "description": "Callback endpoint для Auth - получает code от ESIA и редиректит на фронтенд",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "OAuth Callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "State parameter",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to frontend with code"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    }
                }
            }
        },
        "/users/auth/login": {
            "get": {
                "description": "Перенаправление на ESIA для авторизации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "OAuth Login",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/users/auth/token": {
            "post": {
                "description": "Обмен authorization code на access и refresh токены (как в Keycloak)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Exchange Code for Tokens",
                "parameters": [
                    {
                        "description": "Code и State",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.exchangeTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.exchangeTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    }
                }
            }
        },
        "/users/pong": {
            "get": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Pong",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pong"
                ],
                "summary": "Pong",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/profile": {
            "get": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Get user profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.getProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    }
                }
            }
        },
        "/users/update-info": {
            "post": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Register user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "User Update Info",
                "parameters": [
                    {
                        "description": "User update info request",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.userUpdateInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ErrorStruct": {
            "type": "object",
            "properties": {
                "ErrorCode": {
                    "type": "integer"
                },
                "ErrorMessage": {
                    "type": "string"
                }
            }
        },
<<<<<<< HEAD
        "domain.City": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
=======
        "v1.benefitResponse": {
            "type": "object",
            "properties": {
                "city_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "how_to_use": {
>>>>>>> main
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
<<<<<<< HEAD
                "name": {
                    "type": "string"
=======
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
>>>>>>> main
                },
                "region_id": {
                    "type": "string"
                },
<<<<<<< HEAD
                "updated_at": {
=======
                "requirement": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "target_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "valid_from": {
                    "type": "string"
                },
                "valid_to": {
>>>>>>> main
                    "type": "string"
                }
            }
        },
<<<<<<< HEAD
        "domain.GroupType": {
            "type": "string",
            "enum": [
                "pensioners",
                "disabled",
                "young_families",
                "low_income",
                "students",
                "large_families",
                "children",
                "veterans"
            ],
            "x-enum-varnames": [
                "Pensioners",
                "Disabled",
                "YoungFamilies",
                "LowIncome",
                "Students",
                "LargeFamilies",
                "Children",
                "Veterans"
            ]
=======
        "v1.benefitsListResponse": {
            "type": "object",
            "properties": {
                "benefits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.benefitResponse"
                    }
                }
            }
>>>>>>> main
        },
        "v1.exchangeTokenRequest": {
            "type": "object",
            "required": [
                "code",
                "state"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "v1.exchangeTokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "v1.getProfileResponse": {
            "type": "object",
            "properties": {
                "city_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "external_id": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "group_type": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GroupType"
                    }
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "middle_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "snils": {
                    "type": "string"
                }
            }
        },
        "v1.userUpdateInfoRequest": {
            "type": "object",
            "required": [
                "city_id",
                "group_type"
            ],
            "properties": {
                "city_id": {
                    "type": "string"
                },
                "group_type": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GroupType"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "UserAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfointernal holds exported Swagger Info so clients can modify it
var SwaggerInfointernal = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Backend API",
	Description:      "Backend API",
	InfoInstanceName: "internal",
	SwaggerTemplate:  docTemplateinternal,
}

func init() {
	swag.Register(SwaggerInfointernal.InstanceName(), SwaggerInfointernal)
}
